# -*- coding: utf-8 -*-
"""project traffic vdoipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3WJPp_hqKEgLz6Yw8eYaDXPaEGHI9cB
"""

!pip install ultralytics opencv-python

import cv2
from ultralytics import YOLO
from google.colab.patches import cv2_imshow # Import cv2_imshow for Colab compatibility

# -----------------------
# CONFIGURATION
# -----------------------
VIDEO_PATH = "/content/traffic.mp4"
OUTPUT_PATH = "output_detected.mp4"
MODEL_PATH = "yolov8m.pt"   # change to yolov8l.pt for higher accuracy
CONF = 0.3

# COCO vehicle classes
VEHICLE_CLASSES = {
    2: "Car",
    3: "Motorcycle",
    5: "Bus",
    7: "Truck"
}

COLORS = {
    "Car": (0, 0, 255),
    "Motorcycle": (0, 255, 0),
    "Bus": (255, 0, 0),
    "Truck": (0, 255, 255)
}

# -----------------------
# LOAD MODEL
# -----------------------
model = YOLO(MODEL_PATH)

cap = cv2.VideoCapture(VIDEO_PATH)

width = int(cap.get(3))
height = int(cap.get(4))
fps = int(cap.get(cv2.CAP_PROP_FPS))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(OUTPUT_PATH, fourcc, fps, (width, height))

# Store unique vehicle IDs
counted_ids = set()

print("Processing Video...")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    results = model.track(frame, persist=True, conf=CONF)

    if results[0].boxes.id is not None:
        for box, track_id in zip(results[0].boxes, results[0].boxes.id):

            cls = int(box.cls[0])
            if cls in VEHICLE_CLASSES:

                counted_ids.add(int(track_id))

                label = VEHICLE_CLASSES[cls]
                color = COLORS[label]

                x1, y1, x2, y2 = map(int, box.xyxy[0])

                cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
                cv2.putText(frame, f"{label} ID:{int(track_id)}",
                            (x1, y1-5),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.6, color, 2)

    # Display total count
    cv2.rectangle(frame, (0,0), (420,70), (0,0,0), -1)
    cv2.putText(frame, f"Total Vehicles: {len(counted_ids)}",
                (20,45),
                cv2.FONT_HERSHEY_SIMPLEX,
                1, (0,255,255), 3)

    out.write(frame)

    cv2_imshow(frame) # Changed cv2.imshow to cv2_imshow
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
out.release()
cv2.destroyAllWindows()

print("Done.")
print("Final Vehicle Count:", len(counted_ids))
print("Saved as:", OUTPUT_PATH)